spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gigbookingapp?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

    # The username and password can be discussed later
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # log format
    #call-setters-on-nulls: true
  mapper-locations: classpath*:uk/gigbookingapp/backend/xml/*.xml
  #config-location: classpath:mybatis-config.xml

logging:
  pattern:
    dateformat: dd-MM-yyyy' 'HH:mm:ss.SSS' 'XXX
  file:
    path: ./target/log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{dd-MM-yyyy}.%i.gz
      max-file-size: 1MB


